version: "3.8"
services:
  wildsalfmcp:
    image: wildsdocker/wildsalfmcp:v1
    ports:
      - 8000:8000
    environment:
      BASE_URL: "http://localhost:8080"
      user: "admin"
      pass: "admin"
      FASTMCP_HOST: 0.0.0.0
